### ISSUE TITLE
Image rotation on android

### ISSUE THREAD

**Issue by npomfret** [bamlab/react-native-image-resizer#36]
I've got an issue with some images being rotated incorrectly.  Not sure what the problem is, indeed even how to reproduce reliably.  But here's an example, the original large image gets resized to a thumbnail but its upside down.  If you view the original in a browser window on its own it appears the correct way up, but the thumbnail never does.

![thumbnail](https://cloud.githubusercontent.com/assets/5489469/17809199/d1d816e4-660c-11e6-859e-35789747db28.jpg)

Original:
![original](https://cloud.githubusercontent.com/assets/5489469/17809203/d8c1f880-660c-11e6-9847-9b5394c30946.jpg)

**Comment by superandrew213** [comment]
Your images look the same. Im having a similar issue. Some images are getting rotated by 90 degrees for both iOS and android.

**Comment by superandrew213** [comment]
@npomfret try setting rotation to 1 degree.

**Comment by smilechun** [comment]
My solution:
// Rotate if neccesary
        Bitmap rotatedImage = scaledImage;
        if (rotation >= 0) {
            int orientation = getOrientation(context, Uri.parse(imagePath));
            rotation = orientation + rotation;
            rotatedImage = ImageResizer.rotateImage(scaledImage, rotation);
        }

**Comment by superandrew213** [comment]
[#42](https://github.com/bamlab/react-native-image-resizer/pull/42)

**Comment by 4ian** [comment]
Closing this as fixed by https://github.com/bamlab/react-native-image-resizer/pull/42 :)

**Comment by Volekss** [comment]
I'm still having this bug with "react-native-image-resizer": "^1.3.0"
Any chances @4ian could help me?

**Comment by anhdo9797** [comment]
> I'm still having this bug with "react-native-image-resizer": "^1.3.0"
> Any chances @4ian could help me?

same issue
